const redisClient = require("../config/redis");
const logger = require("../utils/logger");

const fraudGuard = async (req, res, next) => {
    try {
        const deviceId = req.headers["x-device-id"]; // Generated by frontend FingerprintJS
        const ip = req.headers["x-forwarded-for"] || req.connection.remoteAddress;
        
        // Log telemetry for monitoring purposes
        logger.debug(`[FraudGuard] Request from IP: ${ip} | Device: ${deviceId || 'N/A'}`);

        // Simple Rule: Identify missing device signatures (Potential Bot/Scripting API attack)
        if (!deviceId) {
            logger.warn(`[FraudGuard] Request to sensitive endpoint missing X-Device-Id from IP: ${ip}`);
            // Can be configured to block later (`return res.status(403).json(...)`)
        } else {
            // Track Velocity (e.g. 5 requests / 15 mins) on sensitive routes quietly
            const velocityKey = `velocity:ip:${ip}:device:${deviceId}`;
            const attempts = await redisClient.incr(velocityKey);
            
            // Set 15 min expiration only on first hit
            if (attempts === 1) {
                await redisClient.expire(velocityKey, 900);
            }

            // High velocity check (Shadow logging for now, NOT blocking to prevent false bans initially)
            if (attempts > 5) {
                logger.warn(`[FraudGuard Alert] Suspicious Velocity - IP: ${ip} | Device: ${deviceId} hit sensitive endpoint ${attempts} times in 15m.`);
            }
        }
        
    } catch (e) {
        // Fraud guard should *never* crash external legitimate requests. Silently fail.
        logger.error(`[FraudGuard Error] ${e.message}`);
    }
    
    // Always pass to the actual controller safely
    next();
};

module.exports = fraudGuard;
